### ISSUE TITLE
"System-wide" symlinks

### ISSUE THREAD

**Issue by fxquah** [fxquah/QandA#1]
## Example problem
```
cd ~
mkdir symlink_help
cd symlink_help
mkdir destination101
```

Create symbolic link to `symlink_help/destination`.
```
ln -s destination101/ symlink101
```

Now, say I'm in another folder (i.e. the home directory). To use the symlink, I need to type:
```
cd ~
cd symlink_help/symlink101
```

## What I'm after
Is there a way to allow me to use the symbolic link I created system-wide? I tried to add that folder to my `$PATH`. But that didn't work.
```
export PATH=$HOME/symlink_help:$PATH
cd symlink101      # doesn't work
```

What I'm after is something similar to the ability to use binaries in /usr/local/bin regardless of where I am. I haven't tried putting the symlinks in my binaries, but I read that that is not good in terms of security.

**Comment by shouldsee** [comment]
Hi Fu, I have little to say about security cuz my knowledge does not allow me to speculate it. If you would like to do “cd symlink101” regardless of your working directory, it would be some functionality I haven’t heard of. This is because system paths without a starting slash “/“ would always map to a relative path. Hence “cd symlink101” would always map to “cd $PWD/symlink101”, and it would be overwhelming to create the same symlinks in all possibilities of $PWD.

To achieve what you want, however, you can either symlink to an absolute directory say “

**Comment by fxquah** [comment]
Both are great suggestions, and suit different purposes for me. Thanks!
